### ISSUE TITLE
Questions about High-Density Connector Interfaces

### ISSUE THREAD

**Issue by shulltronics** [arduino/portentax8-stm32h7-fw#3]
Hello!

Thank you all for publishing this firmware. In the Portenta x8 datasheet, it states that the firmware running on the H7 core is "proprietary and inaccessible to the user" which initially scared me (other open-source enthusiasts might feel similarly), but I'm really happy to have found this repository.

My question has to do with what interfaces on the H7 core are exposed via the High-Density Connectors. It seems that the purpose of this firmware is largely to present these electrical interfaces as Linux devices on the x8, without the programmer having to write firmware for the M7 core, and because of this the pinout diagrams for the high-density connectors isn't clear about which pins go to the H7 vs the iMX8. I'm interested in doing something such as porting ArduPilot to run on the x8, and leveraging the full power of the M7 and M4 cores for real-time control, even if it means losing some of the interfaces within Linux.

I can see on page 15 of the [full schematics](https://docs.arduino.cc/static/c92dbfc6c6a7c3f79c9987d36f017e48/ABX00049-schematics.pdf) some of the details of which pins go to the H7 vs the iMX8. Similarly, it is clear that the H7 can talk to the iMX8 via the SPI interface that is outlined in this repo, but is there any other interface that connects them (such as USB?). Is there any easier way to tell (other than parsing through the schematic) which pins connect the processors together, and which pins on the HDCs go to which processor?

Thanks for any insight you all can provide! If I can clear up some of these details, I'm looking forward to buying an x8.

**Comment by facchinm** [comment]
Hi @shulltronics ,
first of all, thanks for your interest in this project!
About the scary notice in the datasheet I'm asking the @arduino/ft_content team to amend it :slightly_smiling_face: 

For the HD connectors pinout, you should find some interesting information in this document https://docs.google.com/spreadsheets/d/1dRwgXdNmn4iB_cCIJYsdy5FxVLnAttHKCWpWFFcFZZI/edit?usp=sharing which expands what you can find in the [pinout file](https://docs.arduino.cc/static/019dd9ac3b08f48192dcb1291d37aab9/ABX00049-full-pinout.pdf) and in the [source code](https://github.com/arduino/portentax8-stm32h7-fw/blob/0980463690b39a91d5effad1ceae00cb06e11684/src/gpio.c#L46-L86) .

About the communication between the processors, we have a full SPI interface and some "spare" pins

X8 / H7 extra pins: |   |   | imx8 gpio | H7 pin
-- | -- | -- | -- | --
  | SWD |   | 8 | PA_13 (SWDIO)
  |   |   | 15 | PA_14 (SWCLK)
  | RESET |   | 10 | RESET
  | BOOT0 |   | 11 | BOOT0
  | SPARE (free for user code) |   | 7 | PA_0
  |   |   | 9 | PC_1
  |   |   | 14 | PE_5

Hope this helps, let me know if you have any doubt!

**Comment by shulltronics** [comment]
@facchinm Thank you so much for pointing me to these documents. I will close this issue -- but I'm sure others might find it useful in the future. Thanks again!
